name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 131429175281
  SERVICE: ds553-service
  REGION: us-central1
  DOCKERHUB_REPO: wegold/ds553

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    # - name: Docker Auth
    #   id: docker-auth
    #   uses: 'docker/login-action@v1'
    #   with:
    #     username: 'oauth2accesstoken'
    #     password: '${{ steps.auth.outputs.access_token }}'
    #     registry: '${{ vars.REGION }}-docker.pkg.dev'

    # - name: Build, tag and push container
    #   id: build-image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: ${{ vars.code_directory }}
    #     push: true 
    #     tags: |
    #       ${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ inputs.ref }}

    - name: Create Service declaration   
      run: |-
        export CONTAINER_IMAGE="docker.io/wegold/ds553"
        export SERVICE_NAME="${{ env.SERVICE }}"
        export PROJECT_ID="${{ env.PROJECT_ID }}"
        export REVISION_TAG="${{ inputs.ref }}"
        export CLOUD_RUN_SA="${{ env.CLOUD_RUN_SA }}"
        export ENVIRONMENT="${{ inputs.environment }}"
        envsubst < ./service-yaml/container.yaml > container-${{ inputs.environment }}.yaml
        cat container-${{ inputs.environment }}.yaml
      
      # export CONTAINER_IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ inputs.ref }}"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        metadata: container-${{ inputs.environment }}.yaml