name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 131429175281
  SERVICE: ds553-service
  REGION: us-central1
  DOCKERHUB_REPO: wegold/ds553

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v3'
      with:
        service: '${{ env.SERVICE }}'
        image: 'docker.io/${{ env.DOCKERHUB_REPO }}'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'