name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  SERVICE: ds553-service
  REGION: us-central1
  DOCKERHUB_REPO: wegold/ds553

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Google Cloud (Workload Identity Federation)
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      # ---- Docker Hub login ----
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- Build and Push Docker image to Docker Hub ----
    #   - name: Build and Push Image
    #     run: |
    #         docker buildx build --platform linux/amd64 -t ${{ env.DOCKERHUB_REPO }}:${{ github.sha }} . --push

      # ---- Deploy to Cloud Run ----
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: docker.io/${{ env.DOCKERHUB_REPO }} #:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
